/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fitness.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -1.56]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['material0_0.002']} geometry={nodes.high_polyMesh1_material0_0.geometry} />
          <group position={[-36.76, 0, 0.29]} rotation={[0, 0.06, 0]}>
            <mesh
              material={materials['material0.001']}
              geometry={nodes.back.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.biceps.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.calves.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.chest.geometry}
              position={[60.75, 56.37, 186.04]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.core.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.forearms.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.glutes.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.hamstrings.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.quads.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.remaining_body.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.shoulders.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
            <mesh
              material={materials['material0.001']}
              geometry={nodes.triceps.geometry}
              position={[60.65, 56.06, 186.17]}
              rotation={[-0.38, 0.02, 0]}
              scale={[0.29, 0.22, 0.27]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fitness.glb')
